import * as fs from 'fs-extra';
import * as path from 'path';

export interface UnityProjectParams {
  projectName: string;
  projectPath: string;
  gameType?: 'top-down-shooter' | 'side-scrolling-shooter' | 'space-shooter';
  includeAssets?: boolean;
}

export class UnityProjectService {
  async createProject(params: UnityProjectParams) {
    const fullPath = path.resolve(params.projectPath, params.projectName);

    // Create directory structure
    await this.createDirectoryStructure(fullPath);

    // Create Unity project files
    await this.createProjectSettings(fullPath, params.projectName);
    await this.createGitignore(fullPath);
    await this.createReadme(fullPath, params);

    // Create initial scene
    await this.createInitialScene(fullPath);

    return {
      success: true,
      projectPath: fullPath,
      message: `Successfully created Unity project "${params.projectName}"`,
    };
  }

  private async createDirectoryStructure(projectPath: string) {
    const dirs = [
      'Assets/Scenes',
      'Assets/Scripts/Player',
      'Assets/Scripts/Enemies',
      'Assets/Scripts/Weapons',
      'Assets/Scripts/Managers',
      'Assets/Scripts/UI',
      'Assets/Prefabs/Player',
      'Assets/Prefabs/Enemies',
      'Assets/Prefabs/Weapons',
      'Assets/Prefabs/UI',
      'Assets/Materials',
      'Assets/Sprites',
      'Assets/Audio',
      'ProjectSettings',
      'Packages',
    ];

    for (const dir of dirs) {
      await fs.ensureDir(path.join(projectPath, dir));
    }
  }

  private async createProjectSettings(projectPath: string, projectName: string) {
    const projectVersion = {
      m_EditorVersion: '2022.3.0f1',
      m_EditorVersionWithRevision: '2022.3.0f1 (fb119bb0b476)',
    };

    await fs.writeJson(
      path.join(projectPath, 'ProjectSettings/ProjectVersion.txt'),
      projectVersion,
      { spaces: 2 }
    );

    // Create basic ProjectSettings.asset
    const projectSettings = `%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!129 &1
PlayerSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 23
  productName: ${projectName}
  defaultCompanyName: DefaultCompany
  defaultCursor: {fileID: 0}
  cursorHotspot: {x: 0, y: 0}
  m_SplashScreenBackgroundColor: {r: 0.13725491, g: 0.12156863, b: 0.1254902, a: 1}
  m_ShowUnitySplashScreen: 1
  m_ShowUnitySplashLogo: 1
  m_SplashScreenStyle: 1
  m_AndroidProfiler: 0
  AndroidProfilerState: 0
  m_AndroidBanner: {fileID: 0}
  androidGamepadSupportLevel: 0
  resolutionScalingMode: 0
  m_TargetPixelDensity: 30
`;

    await fs.writeFile(
      path.join(projectPath, 'ProjectSettings/ProjectSettings.asset'),
      projectSettings
    );
  }

  private async createGitignore(projectPath: string) {
    const gitignore = `# Unity generated
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Uu]ser[Ss]ettings/

# MemoryCaptures
/[Mm]emoryCaptures/

# Asset meta data
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated meta files
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.aab
*.unitypackage
*.app

# Crashlytics
crashlytics-build.properties

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D Generated File On Crash Reports
sysinfo.txt

# Builds
*.apk
*.unitypackage

# macOS
.DS_Store

# Windows
Thumbs.db
ehthumbs.db

# JetBrains Rider
.idea/
*.sln.iml`;

    await fs.writeFile(path.join(projectPath, '.gitignore'), gitignore);
  }

  private async createReadme(projectPath: string, params: UnityProjectParams) {
    const readme = `# ${params.projectName}

A Unity 2D shooter game created with Unity MCP.

## Game Type
${params.gameType || 'top-down-shooter'}

## Controls
- **Movement**: WASD or Arrow Keys
- **Shoot**: Space or Left Click
- **Pause**: ESC

## Project Structure
- \`Assets/Scenes/\`: Game scenes
- \`Assets/Scripts/\`: C# scripts
- \`Assets/Prefabs/\`: Reusable game objects
- \`Assets/Sprites/\`: 2D sprites
- \`Assets/Audio/\`: Sound effects and music

## Requirements
- Unity 2022.3 LTS or later

## Getting Started
1. Open project in Unity Editor
2. Open the MainScene in \`Assets/Scenes/\`
3. Press Play to test the game

Generated with Unity MCP Server
`;

    await fs.writeFile(path.join(projectPath, 'README.md'), readme);
  }

  private async createInitialScene(projectPath: string) {
    const sceneYaml = `%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!29 &1
OcclusionCullingSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_OcclusionBakeSettings:
    smallestOccluder: 5
    smallestHole: 0.25
    backfaceThreshold: 100
  m_SceneGUID: 00000000000000000000000000000000
  m_OcclusionCullingData: {fileID: 0}
--- !u!104 &2
RenderSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 9
  m_Fog: 0
  m_FogColor: {r: 0.5, g: 0.5, b: 0.5, a: 1}
  m_FogMode: 3
  m_FogDensity: 0.01
  m_LinearFogStart: 0
  m_LinearFogEnd: 300
  m_AmbientSkyColor: {r: 0.212, g: 0.227, b: 0.259, a: 1}
  m_AmbientIntensity: 1
  m_AmbientMode: 3
  m_SubtractiveShadowColor: {r: 0.42, g: 0.478, b: 0.627, a: 1}
  m_SkyboxMaterial: {fileID: 0}
  m_HaloStrength: 0.5
  m_FlareStrength: 1
  m_FlareFadeSpeed: 3
  m_HaloTexture: {fileID: 0}
  m_SpotCookie: {fileID: 10001, guid: 0000000000000000e000000000000000, type: 0}
  m_DefaultReflectionMode: 0
  m_DefaultReflectionResolution: 128
  m_ReflectionBounces: 1
  m_ReflectionIntensity: 1
  m_CustomReflection: {fileID: 0}
  m_Sun: {fileID: 0}
  m_IndirectSpecularColor: {r: 0, g: 0, b: 0, a: 1}
  m_UseRadianceAmbientProbe: 0
--- !u!157 &3
LightmapSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 12
  m_GIWorkflowMode: 1
--- !u!196 &4
NavMeshSettings:
  serializedVersion: 2
  m_ObjectHideFlags: 0
  m_BuildSettings:
    serializedVersion: 2
  m_NavMeshData: {fileID: 0}
--- !u!1 &519420028
GameObject:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  serializedVersion: 6
  m_Component:
  - component: {fileID: 519420032}
  - component: {fileID: 519420031}
  - component: {fileID: 519420029}
  m_Layer: 0
  m_Name: Main Camera
  m_TagString: MainCamera
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 1
--- !u!81 &519420029
AudioListener:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 519420028}
  m_Enabled: 1
--- !u!20 &519420031
Camera:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 519420028}
  m_Enabled: 1
  serializedVersion: 2
  m_ClearFlags: 2
  m_BackGroundColor: {r: 0.19215687, g: 0.3019608, b: 0.4745098, a: 0}
  m_projectionMatrixMode: 1
  m_GateFitMode: 2
  m_FOVAxisMode: 0
  m_SensorSize: {x: 36, y: 24}
  m_LensShift: {x: 0, y: 0}
  m_FocalLength: 50
  m_NormalizedViewPortRect:
    serializedVersion: 2
    x: 0
    y: 0
    width: 1
    height: 1
    m_validationHeight: 1
  near clip plane: 0.3
  far clip plane: 1000
  field of view: 60
  orthographic: 1
  orthographic size: 5
  m_Depth: -1
  m_CullingMask:
    serializedVersion: 2
    m_Bits: 4294967295
  m_RenderingPath: -1
  m_TargetTexture: {fileID: 0}
  m_TargetDisplay: 0
  m_TargetEye: 0
  m_HDR: 1
  m_AllowMSAA: 0
  m_AllowDynamicResolution: 0
  m_ForceIntoRT: 0
  m_OcclusionCulling: 0
  m_StereoConvergence: 10
  m_StereoSeparation: 0.022
--- !u!4 &519420032
Transform:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 519420028}
  m_LocalRotation: {x: 0, y: 0, z: 0, w: 1}
  m_LocalPosition: {x: 0, y: 0, z: -10}
  m_LocalScale: {x: 1, y: 1, z: 1}
  m_Children: []
  m_Father: {fileID: 0}
  m_RootOrder: 0
  m_LocalEulerAnglesHint: {x: 0, y: 0, z: 0}
`;

    await fs.writeFile(
      path.join(projectPath, 'Assets/Scenes/MainScene.unity'),
      sceneYaml
    );

    // Create .meta file for scene
    const metaContent = `fileFormatVersion: 2
guid: ${this.generateGuid()}
DefaultImporter:
  externalObjects: {}
  userData:
  assetBundleName:
  assetBundleVariant:
`;

    await fs.writeFile(
      path.join(projectPath, 'Assets/Scenes/MainScene.unity.meta'),
      metaContent
    );
  }

  private generateGuid(): string {
    return 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'.replace(/x/g, () => {
      return Math.floor(Math.random() * 16).toString(16);
    });
  }
}
